### PR TITLE
Support to run with DOCKER_* env variables

### PR DESCRIPTION
**Pull request by achied**
This commit allows dockercli to use the DOCKER_* variables and works with docker
remote API and Swarm, by example.

### CODE REVIEW

**Comment by j-bennet** [comment]
AutoVersionClient constructor already sets 'version' to 'auto'. Any particular reason to use Client constructor?

**Comment by achied** [comment]
You are right. There is not special reason. I can use AutoVersionClient constructor.

**Comment by j-bennet** [comment]
Looks good. What was the problem before this fix? Did you have an SSL error when running dockercli?

**Comment by achied** [comment]
I am using swarm and with the previous code and  I can only work with the local socket.  TLS communication doesn't work because the client instance is never configured to use it.

**Comment by j-bennet** [comment]
Thanks for the PR. Merging.

**Pull request merged**
